baseURL: https://ehubio.github.io/hwe
languageCode: en-us
title: SCI1116 Genetics & Evolution
theme: "PaperMod"
params:
  defaultTheme: light
  homeInfoParams:
    Content: Set allele frequencies and effective population size